services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - devpulse_network

  worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: celery -A app.workers.celery worker --loglevel=info
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - devpulse_network

  beat:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: celery -A app.workers.celery beat --loglevel=info
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - devpulse_network

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - devpulse_network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - devpulse_network

volumes:
  db_data:
    driver: local

networks:
  devpulse_network:
    driver: bridge
